"""add mock interview sessions table

Revision ID: 1b7602d943e0
Revises: d3a1bfdd8164
Create Date: 2026-08-21 08:54:20.114726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7602d943e0'
down_revision: Union[str, Sequence[str], None] = 'd3a1bfdd8164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_interview_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.Integer(), nullable=True),
    sa.Column('skill_gap_report_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('questions_answers', sa.Text(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weak_areas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_gap_report_id'], ['skill_gap_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interview_sessions_job_description_id'), 'mock_interview_sessions', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_mock_interview_sessions_resume_id'), 'mock_interview_sessions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_mock_interview_sessions_skill_gap_report_id'), 'mock_interview_sessions', ['skill_gap_report_id'], unique=False)
    op.create_index(op.f('ix_mock_interview_sessions_user_id'), 'mock_interview_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_interview_sessions_user_id'), table_name='mock_interview_sessions')
    op.drop_index(op.f('ix_mock_interview_sessions_skill_gap_report_id'), table_name='mock_interview_sessions')
    op.drop_index(op.f('ix_mock_interview_sessions_resume_id'), table_name='mock_interview_sessions')
    op.drop_index(op.f('ix_mock_interview_sessions_job_description_id'), table_name='mock_interview_sessions')
    op.drop_table('mock_interview_sessions')
    # ### end Alembic commands ###
