"""add cached chat response payload

Revision ID: 25e1f88f381b
Revises: 9f18b040e5e3
Create Date: 2026-08-26 21:06:05.554525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e1f88f381b'
down_revision: Union[str, Sequence[str], None] = '9f18b040e5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_payload')
    # ### end Alembic commands ###
