"""add skill gap portfolio project prompts

Revision ID: 4aa96709ec46
Revises: be47ebc7390c
Create Date: 2026-08-27 20:13:29.649362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa96709ec46'
down_revision: Union[str, Sequence[str], None] = 'be47ebc7390c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap_reports', sa.Column('portfolio_project_prompts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap_reports', 'portfolio_project_prompts')
    # ### end Alembic commands ###
