"""add agent conversation message mode

Revision ID: be47ebc7390c
Revises: 25e1f88f381b
Create Date: 2026-08-27 14:16:59.319030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be47ebc7390c'
down_revision: Union[str, Sequence[str], None] = '25e1f88f381b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('mode', sa.String(length=20), server_default='chat', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'mode')
    # ### end Alembic commands ###
