from datetime import datetime
from typing import Literal

from pydantic import (
    BaseModel,
    Field,
)


# ==================================================
# INTERVIEW TYPES
# ==================================================


InterviewType = Literal[
    "technical",
    "behavioral",
    "hr",
    "mixed",
]


# ==================================================
# START INTERVIEW
# ==================================================


class MockInterviewStartRequest(BaseModel):
    """
    Request sent when the user starts a new
    Mock Interview session.

    user_id is intentionally NOT accepted from
    the frontend because ownership comes from
    the authenticated JWT user.
    """

    resume_id: int = Field(
        ...,
        gt=0,
    )

    job_description_id: int | None = Field(
        default=None,
        gt=0,
    )

    skill_gap_report_id: int | None = Field(
        default=None,
        gt=0,
    )

    interview_type: InterviewType = "mixed"

    total_questions: int = Field(
        default=5,
        ge=3,
        le=10,
    )


# ==================================================
# QUESTION
# ==================================================


class InterviewQuestion(BaseModel):
    """
    One question generated by CareerPilot.
    """

    question_number: int = Field(
        ...,
        ge=1,
    )

    question: str = Field(
        ...,
        min_length=1,
    )

    skill_target: str | None = None

    interview_type: InterviewType | None = None


# ==================================================
# START INTERVIEW RESPONSE
# ==================================================


class MockInterviewStartResponse(BaseModel):
    """
    Returned after creating the session and
    generating the first question.
    """

    session_id: int

    status: str

    total_questions: int

    current_question: InterviewQuestion


# ==================================================
# SUBMIT ANSWER
# ==================================================


class MockInterviewAnswerRequest(BaseModel):
    """
    Submit an answer for the current question.

    The backend determines which question is active
    using the persisted session state.
    """

    session_id: int = Field(
        ...,
        gt=0,
    )

    answer: str = Field(
        ...,
        min_length=1,
        max_length=5000,
    )


# ==================================================
# ANSWER FEEDBACK
# ==================================================


class InterviewAnswerFeedback(BaseModel):
    """
    Structured feedback for one submitted answer.
    """

    score: float = Field(
        ...,
        ge=0,
        le=10,
    )

    feedback: str

    strengths: list[str] = Field(
        default_factory=list,
    )

    improvements: list[str] = Field(
        default_factory=list,
    )

    better_answer_approach: str | None = None


# ==================================================
# ANSWER RESPONSE
# ==================================================


class MockInterviewAnswerResponse(BaseModel):
    """
    Returned after evaluating one answer.

    If the interview still has questions remaining,
    next_question contains the next generated
    question.

    If the interview has finished,
    completed=True and next_question=None.
    """

    session_id: int

    completed: bool

    answered_question_number: int

    feedback: InterviewAnswerFeedback

    next_question: InterviewQuestion | None = None


# ==================================================
# STORED QUESTION / ANSWER RECORD
# ==================================================


class InterviewQuestionAnswerRecord(BaseModel):
    """
    Representation of one persisted question and
    its evaluated answer.

    This corresponds to one object inside the
    questions_answers JSON stored in MySQL.
    """

    question_number: int

    question: str

    skill_target: str | None = None

    interview_type: InterviewType | None = None

    answer: str | None = None

    feedback: str | None = None

    score: float | None = Field(
        default=None,
        ge=0,
        le=10,
    )

    strengths: list[str] = Field(
        default_factory=list,
    )

    improvements: list[str] = Field(
        default_factory=list,
    )

    better_answer_approach: str | None = None


# ==================================================
# FINAL SESSION SUMMARY
# ==================================================


class MockInterviewSummary(BaseModel):
    """
    Final interview result generated after all
    questions have been answered.
    """

    readiness_score: float = Field(
        ...,
        ge=0,
        le=100,
    )

    overall_feedback: str

    strengths: list[str] = Field(
        default_factory=list,
    )

    weak_areas: list[str] = Field(
        default_factory=list,
    )

    recommended_next_steps: list[str] = Field(
        default_factory=list,
    )


# ==================================================
# COMPLETED SESSION RESPONSE
# ==================================================


class MockInterviewSessionResponse(BaseModel):
    """
    Full representation of a Mock Interview session.

    Used by historical interview retrieval and the
    final interview summary screen.
    """

    id: int

    resume_id: int

    job_description_id: int | None = None

    skill_gap_report_id: int | None = None

    status: str

    total_questions: int

    current_question_index: int

    questions_answers: list[
        InterviewQuestionAnswerRecord
    ] = Field(
        default_factory=list,
    )

    overall_feedback: str | None = None

    readiness_score: float | None = None

    strengths: list[str] = Field(
        default_factory=list,
    )

    weak_areas: list[str] = Field(
        default_factory=list,
    )

    created_at: datetime

    completed_at: datetime | None = None

    model_config = {
        "from_attributes": True,
    }